default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: billing
  username: pantera
  password: "#5MinutesAlone."
  host: 172.16.1.21

development:
  <<: *default
  database: billing_development

test:
  <<: *default
  database: billing_test

production:
  <<: *default
  database: billing
  username: pantera
  password: "#5MinutesAlone."